name: Unittests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Nix cache
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05

      - name: It compiles
        run: nix build

      - name: Run the unittests
        run: nix run .#unit_tests
